permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Hao Guo
  email: napoleon1889@163.com
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/napoleon1889
  music: http://site.douban.com/linanya
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 蝈蝈的博客
description: 面壁者的宝库
#url: http://painterlin.com
url: http://napoleon1889.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  #id: UA-54262064-1 
  id: UA-77335153-1
  #url: painterlin.com
  url: napoleon1889.github.io

# disqus 设置
#disqus:
  #shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档